### ISSUE TITLE
Loadout wearable Issues Mega checklist

### ISSUE THREAD

**Issue by CypressBz** [hrzntal/horizon#1080]
Hello! I've gone through and made this a master list of all the current loadout issues as of the 3rd of June, 2022
This list Should be exhaustive, but if any additional issues are spotted, let me know in the comments and I'll update the list.
 
###**Technical issues, or small missing pixels issues**
 
###Uniforms
- [ ] Henchmen jumpsuit exists in loadout
- [ ] Yellow performer skirt has 3 or 4 missing pixels behind the leg's side views on digi variant
- [ ] black fashionable dress 1/2 and traditional dress have the same issue as above the top is shifted to the side as well
- [ ] Camo pants AND Tacticool turtleneck missing two pixels on the inner thigh on front, 1 pixel at the back of legs on side on Digi variant
- [ ] Camo pants in shorts list on loadout despite being pants

###Suit Issue
- [ ] Simple tailored coat's color 3 gags overlay is shifted one pixel forward on the side views.
- [ ] Coveralls Are entirely unfinished
- [ ] Tailored Winter Coat #1079

### Neck
 - [ ] Tailored Cloak/veil/shroud/boatcloak have full black pixels that are unsightly

### Feet
 - [ ] Silver Leg wraps #1078
 
### Misc
 - [ ] Tenisballs cannot be worn on mask slot, but are on the mouth on both hat and neck slots.

###**This area below is noting everything needing to be converted to sprites supporting digitigrade Mutant body parts.**
 
###Missing Digilegs Variants **Uniforms**
 - [ ] Trishirt
 - [ ] All Cheongsam Variants
 - [ ] All Qipao Variants
 - [ ] Croptop
 - [ ] Henchmen jumpsuit
 - [ ] Red Plaid Skirt
 - [ ] swept skirts
 - [ ] Denim Skirts
 - [ ] striped dress
 - [ ] White Sundress
 - [ ] Sundress
 - [ ] sailor dress
 - [ ] green dress
 - [ ] pink dress
 - [ ] ripped Jeans side/back
 - [ ] jean shorts
 - [ ] red athletics shorts

### Missing Digilegs Variants **Suits**
- [ ] Worn shirt (Ian and plain Versions) [missing 4 pixels on front/back]
- [ ] ladies coat [missing 2 pixels on the front and back]
